import { CalendarDays, MapPin, ArrowUpRight, Ticket } from 'lucide-react';
import Link from 'next/link';
import { readSchedule } from '@/lib/store';
import { today, displayDate, validDate } from '@/lib/date';
import { Agenda } from '@/components/agenda';
export const dynamic = 'force-dynamic';
export default async function Home({ searchParams }: { searchParams: Promise<{ data?: string }> }) {
  const query = await searchParams;
  const {schedule,degraded} = await readSchedule();
  const currentDate = today();
  const initialDate = query.data && validDate(query.data) && query.data.startsWith(schedule.period) ? query.data : currentDate.startsWith(schedule.period) ? currentDate : `${schedule.period}-01`;
  const stale = currentDate.slice(0,7)!==schedule.period || Date.now()-Date.parse(schedule.fetchedAt)>48*3600000;
  const fullPrice = schedule.sessions.find(s=>!s.free)?.price;
  return <main id="conteudo"><section className="hero"><div className="eyebrow"><span className="live-dot"/> JOÃO PESSOA, PARAÍBA <span className="eyebrow-separator">/</span> CINE BANGÜÊ</div><div className="hero-line"><h1>O próximo filme.<br/><em>A próxima conversa.</em></h1><div className="hero-ticket" aria-hidden="true"><span>CINEMA<br/>PÚBLICO</span><div className="ticket-mark">b.</div><span>NO ESPAÇO<br/>CULTURAL</span></div></div><p className="hero-description">Cinema que fica com você. Encontre sua próxima sessão<br className="desktop-break"/> no Espaço Cultural José Lins do Rego.</p><div className="hero-bottom"><span><CalendarDays size={16}/> Programação de {displayDate(`${schedule.period}-01`, {month:'long',year:'numeric'})}</span><a href="/api/v1/calendario">Assinar calendário <ArrowUpRight size={16}/></a></div></section>
    {stale||degraded?<div className="notice"><strong>{degraded?'Exibindo a última programação disponível.':currentDate.slice(0,7)!==schedule.period?'A programação do mês atual ainda não está disponível.':'A programação precisa de uma nova verificação.'}</strong> Última coleta: {displayDate(schedule.fetchedAt.slice(0,10))}. <a href={schedule.sourceUrl} target="_blank" rel="noreferrer">Confira a fonte oficial ↗</a></div>:null}
    <div className="main-grid"><Agenda schedule={schedule} initialDate={initialDate} currentDate={currentDate}/><aside className="cinema-info"><div className="info-card"><div className="eyebrow">NOS ENCONTRAMOS NO CINEMA</div><h2>Uma sala.<br/>Muitos mundos.</h2><p>O Cine Bangüê fica no Espaço Cultural José Lins do Rego, em Tambauzinho.</p><div className="info-rule"/><h3><Ticket size={17}/> Ingressos</h3><div className="prices"><div><span>Inteira</span><strong>{fullPrice?.full != null ? `R$ ${fullPrice.full}`:'Consulte a bilheteria'}</strong></div><div><span>Meia</span><strong>{fullPrice?.half != null ? `R$ ${fullPrice.half}`:'Consulte a bilheteria'}</strong></div></div><p className="small-copy">Venda na bilheteria, 1h antes da primeira sessão do dia. Pagamento em espécie ou Pix. Sessões especiais podem ter condições próprias.</p><div className="info-rule"/><h3><MapPin size={17}/> Como chegar</h3><p className="address">Rua Abdias Gomes de Almeida, 800<br/>Tambauzinho · João Pessoa, PB</p><a className="map-link" href="https://www.google.com/maps/search/?api=1&query=Cine+Bangue+Espaco+Cultural+Joao+Pessoa" target="_blank" rel="noreferrer">Abrir no mapa <ArrowUpRight size={17}/></a></div><div className="source-card"><span className="eyebrow">DE ONDE VÊM OS HORÁRIOS</span><p>Programação da FUNESC, com divergências sinalizadas para conferência.</p><a href={schedule.sourceUrl} target="_blank" rel="noreferrer">Programação oficial em texto <ArrowUpRight size={14}/></a>{schedule.pdfUrl?<a href={schedule.pdfUrl} target="_blank" rel="noreferrer">PDF original <ArrowUpRight size={14}/></a>:null}{schedule.validation?.map(source=><p key={source.url}>{source.status==='fulfilled'?<><a href={source.url} target="_blank" rel="noreferrer">{source.name} ↗</a>{source.matched} horários coincidem com a grade oficial.</>:'Fonte secundária indisponível na última coleta.'}</p>)}<small>Verificada em {new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:schedule.timezone}).format(new Date(schedule.fetchedAt))}.</small><Link href="/api-docs">Reutilize os dados pela API ↗</Link></div></aside></div>
  </main>;
}
