'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { Schedule } from '@/lib/types';
export function ReviewPanel({schedule}:{schedule:Schedule}) {
  const router=useRouter(); const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function post(path:string,body?:unknown) {
    setBusy(true);setMessage('');
    try {const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||'Operação falhou.');setMessage(path.includes('importar')?`${result.sessions} sessões importadas. ${result.issues} divergências para revisar.`:'Alteração registrada.');router.refresh();}
    catch(e){setMessage(e instanceof Error?e.message:'Falha de conexão.');}finally{setBusy(false);}
  }
  return <><button className="primary-button" disabled={busy} onClick={()=>void post('/api/admin/importar')}>{busy?'Processando…':'Atualizar da FUNESC'}</button><p className="admin-message" role="status">{message}</p><h2>Divergências ({schedule.issues.filter(i=>!i.resolved).length} pendentes)</h2><p>A revisão confirma a grade diária. Fontes secundárias não criam sessões. Registre o que foi conferido e a evidência utilizada.</p>{schedule.issues.map(issue=><article className={`review-card ${issue.resolved?'resolved':''}`} key={issue.id}><h3>{issue.message}</h3>{issue.resolved?<p>Revisada: {issue.resolution}</p>:<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void post('/api/admin/revisar',{period:schedule.period,sourceHash:schedule.sourceHash,issueId:issue.id,resolution:form.get('resolution')});}}><label htmlFor={`resolution-${issue.id}`}>Justificativa e fonte da conferência</label><textarea id={`resolution-${issue.id}`} name="resolution" required minLength={12} maxLength={2000}/><button className="primary-button" disabled={busy}>Confirmar grade diária</button></form>}</article>)}<h2>Corrigir um horário</h2><p>Somente sessões já existentes. Informe a evidência que confirma a exibição no Cine Bangüê. A correção não encerra divergências automaticamente e precisa ser reavaliada se a fonte oficial mudar.</p><form className="review-card" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void post('/api/admin/corrigir',{period:schedule.period,sourceHash:schedule.sourceHash,sessionId:form.get('sessionId'),date:form.get('date'),time:form.get('time'),reason:form.get('reason')});}}><div className="admin-fields"><label>Sessão<select name="sessionId" required>{schedule.sessions.map(s=><option key={s.id} value={s.id}>{s.date} {s.time} · {s.title}</option>)}</select></label><label>Data<input type="date" name="date" required min={`${schedule.period}-01`} max={`${schedule.period}-31`}/></label><label>Horário<input type="time" name="time" required/></label></div><label htmlFor="correction-reason">Evidência e justificativa</label><textarea id="correction-reason" name="reason" required minLength={20} maxLength={2000}/><button className="primary-button" disabled={busy}>Salvar correção</button></form></>;
}
