import Link from 'next/link';
export const metadata = { title: 'API pública' };
export default function ApiDocs() {
  return <main id="conteudo" className="document-page"><span className="eyebrow">DADOS ABERTOS · API V1</span><h1>A programação também<br/>é sua para construir.</h1><p>Consulte e reutilize as sessões do <strong>Cine Bangüê</strong>. A API é pública, sem login ou chave. Todas as respostas JSON incluem <code>meta</code> e <code>data</code>.</p><h2>Consultas</h2><table><thead><tr><th>Endpoint</th><th>Resposta</th></tr></thead><tbody><tr><td><Link href="/api/v1/programacao"><code>GET /api/v1/programacao</code></Link></td><td>Sessões e dias explicitamente sem sessão.</td></tr><tr><td><Link href="/api/v1/filmes"><code>GET /api/v1/filmes</code></Link></td><td>Filmes que têm sessões na grade.</td></tr><tr><td><code>GET /api/v1/filmes/:id</code></td><td>Ficha do filme e suas sessões.</td></tr><tr><td><code>GET /api/v1/sessoes/:id</code></td><td>Uma sessão, com filme e avisos.</td></tr><tr><td><Link href="/api/v1/calendario"><code>GET /api/v1/calendario</code></Link></td><td>Calendário iCalendar (.ics).</td></tr></tbody></table><h2>Filtrar por data ou filme</h2><pre>{`GET /api/v1/programacao?inicio=2026-10-07&fim=2026-10-14
GET /api/v1/programacao?filme=ran
GET /api/v1/filmes/ran?inicio=2026-10-01&fim=2026-10-31
GET /api/v1/calendario?filme=ran`}</pre><p>Use datas no formato <code>YYYY-MM-DD</code>. Os limites são inclusivos. Consulte um mês por requisição. Sem filtros, a API retorna a programação do mês atual, se publicada, ou a mais recente disponível. Um mês sem dados retorna <code>404</code>, nunca uma lista que sugira que o cinema está fechado.</p><h2>Um exemplo em JavaScript</h2><pre>{`const resposta = await fetch(
  "https://bangue.vercel.app/api/v1/programacao?filme=ran"
);
if (!resposta.ok) throw new Error("Consulta indisponível");
const { meta, data } = await resposta.json();
console.log(meta.verificadoEm, data.sessions);`}</pre><h2>Como interpretar os dados</h2><p><code>startsAt</code> traz o deslocamento <code>-03:00</code>, e <code>meta.timezone</code> identifica o fuso de João Pessoa. <code>filmId: null</code> representa um programa de curtas, que pode reunir vários filmes.</p><p><code>needsReview</code> e <code>warnings</code> sinalizam divergências ainda não revisadas. Esses horários vêm da grade diária oficial e precisam de conferência. Sessões com divergência aparecem como <code>TENTATIVE</code> no calendário.</p><p><code>meta.verificadoEm</code> informa a última coleta; <code>meta.desatualizada</code> indica mais de 48 horas sem verificação ou um período diferente do mês atual. <code>meta.contingencia</code> sinaliza uso do arquivo de referência após falha no banco.</p><h2>Origem, acesso e disponibilidade</h2><p>A grade diária da FUNESC é a base da programação. Fontes secundárias podem apontar divergências, mas não adicionam filmes ou sessões. O PDF é apenas uma referência acessível pelo site. O TMDb pode fornecer cartazes de filmes já identificados.</p><p>CORS permite consultas de outros sites. As respostas têm cache de até cinco minutos na CDN. O limite é de 120 consultas por minuto por IP na origem; excedê-lo retorna <code>429</code> com <code>Retry-After</code>. Sem banco, o limite é aplicado por instância.</p><p>Ao reutilizar, mantenha a atribuição à FUNESC e o link da fonte. A API não concede direitos sobre cartazes e sinopses. Confirme condições de ingresso e alterações diretamente com o cinema.</p><p><Link href="/">← Voltar à programação</Link></p></main>;
}
